---
title: "Homework04"
author: "Ni Jie"
date: "3/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# WDG: If you put your library calls within the r setup code chunk, it will run automatically before any chunk. (Usually a good idea)
library(here)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(gridExtra)
```


# Input dataset & dictionary

```{r}
# WDG: If you `library(here)` you don't have to use here::here(), you can just use here()
avp <- read_csv(here::here("data", "raw_data", "avp_synth_data.csv"),
  col_types = cols(
    gpa = col_double(),
    age = col_double(),
    gender = col_character(),
    ethnicity = col_character(),
    income = col_character(),
    condition = col_character(),
    .default = col_double()
  ),
  na = c("", "NA", "n/a", "N/A")
)
key <- read_csv(here::here("data", "raw_data", "avp_codebook.csv"),
  col_types = cols(
    Item = col_character(),
    Content = col_character(),
    Options = col_character(),
    Keying = col_double()
  )
)
```


## Clean dataset

#reverse coding & calculate total score for BFI-2 ratings.

```{r}
summary(avp)

# pull reversed items
reversed <- key %>%
  filter(Keying == -1) %>%
  pull(Item)

# reverse
avp_reversed <-
  avp %>%
  mutate(
    across(
      all_of(reversed),
      ~ recode(.x, "5" = 1, "4" = 2, "3" = 3, "2" = 4, "1" = 5)
    )
  )


# calculate total scores
avp_total <-
  avp_reversed %>%
  rowwise() %>%
  mutate(
    ext_tot = mean(c_across(ext1:ext12)),
    agr_tot = mean(c_across(agr1:agr12)),
    con_tot = mean(c_across(con1:con12)),
    neg_tot = mean(c_across(neg1:neg12)),
    ope_tot = mean(c_across(ope1:ope12)),
    health_tot = mean(c_across(health1:health26)),
    work_tot = mean(c_across(work1:work17))
  ) %>%
  select(
    ext_tot, agr_tot, con_tot, neg_tot, ope_tot, health_tot, work_tot,
    gpa, age, gender
  )

summary(avp_total)
```


## plotting

```{r}
# histogram
# WDG: A title is very important when it comes to graphs. Try and answer the question: "What am I looking at?" when thinking of a title.

hist_ext <-
  ggplot(avp_total, aes(x = ext_tot)) +
  geom_histogram(bins = 25)

hist_agr <-
  ggplot(avp_total, aes(x = agr_tot)) +
  geom_histogram(bins = 25)

hist_con <-
  ggplot(avp_total, aes(x = con_tot)) +
  geom_histogram(bins = 25)

hist_neg <-
  ggplot(avp_total, aes(x = neg_tot)) +
  geom_histogram(bins = 25)

hist_ope <-
  ggplot(avp_total, aes(x = ope_tot)) +
  geom_histogram(bins = 25)

# WDG: Check out the patchwork package for arranging multiple graphs
avp_plot <- grid.arrange(hist_ext, hist_agr, hist_con, hist_neg, hist_ope)
``` 


## Output

```{r}
# output cleaned dataset
write_csv(
  avp_total,
  here::here("data", "raw_data", "avp_total.csv")
)
# output bitmap plot
ggsave(
  here::here("output", "figures", "avp_plot.tiff"),
  avp_plot
)
# output vector plot
ggsave(
  here::here("output", "figures", "avp_plot.eps"),
  avp_plot
)
# output pdf plot
ggsave(
  here::here("output", "figures", "avp_plot.pdf"),
  avp_plot
)
``` 
